version: '{build}'
os: Windows Server 2012
build: off
clone_depth: 50
branches:
  except:
    - travis-ci.*

environment:
  matrix:
    - JAVA_HOME: "C:\\Program Files (x86)\\Java\\jdk1.8.0"
    - JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
    - JAVA_HOME: "C:\\Program Files\\Java\\jdk9"
    - JAVA_HOME: "C:\\Program Files\\Java\\jdk10"
    - JAVA_HOME: "C:\\Program Files\\Java\\jdk11"

init:
  - ps: "ls 'C:/Program Files/Java/jdk*'"
  - ps: "ls 'C:/Program Files (x86)/Java/jdk*'"

install:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-Xmx768m -XX:MaxPermSize=128m
  - cmd: SET JAVA_OPTS=-Xmx768m -XX:MaxPermSize=128m
  - "ECHO JAVA_HOME=%JAVA_HOME%, HOMEPATH=%HOMEPATH%, PATH=%PATH%"
  - cmd: ./mvnw.cmd --version

test_script:
  - ./mvnw.cmd clean install --batch-mode
  - ./mvnw.cmd dependency:copy-dependencies -DincludeScope=test -DexcludeArtifactIds=javassist,jsr305
  - echo "Run Agent test"
  - ps: |
      $ttl_jar=Get-ChildItem target\transmittable-thread-local-*.jar -Exclude *-sources.jar | Select-Object -ExpandProperty FullName
      $cp=Get-ChildItem target\dependency\*.jar | Select-Object -ExpandProperty FullName
      $cp=$cp + 'target\test-classes'
      $cp=$cp -join ';'
      echo "java -Xmx256m -Xms256m -javaagent:$ttl_jar -cp $cp -ea com.alibaba.ttl.threadpool.agent.AgentCheck"
      $output=java -Xmx256m -Xms256m -javaagent:$ttl_jar -cp $cp -ea com.alibaba.ttl.threadpool.agent.AgentCheck 2>&1
      $output.CategoryInfo.TargetName | Out-Default

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2\
